### ISSUE TITLE
BGP changes done in https://github.com/Azure/sonic-utilities/pull/102 should be reverted

### ISSUE THREAD

**Issue by nikos-li** [Azure/sonic-utilities#108]
BGP has and supports non-IP address families (l2vpn, ls are such examples) but quagga only supports ipv4 and ipv6. Since sonic cli is newly developed from scratch it should attempt to follow the proper convention of "show bgp <afi> <safi>" at minimum. Vendors have allowed "show ip bgp" to follow the same convention for backwards compatibility reasons. In this case, ip is not really meant to mean or imply ipv4. That is also the reason why under that cli of many vendors, you will see ipv6 options as well as other <afi> options. In sonic we don't need to be backwards compatible since sonic's cli is new. Removing "show bgp" and only allowing "show ip bgp" and "show ipv6 bgp" is a change that not only will cause confusion in the future, but in comparison to "show bgp" less flexible, less desirable. The BGP changes done in https://github.com/Azure/sonic-utilities/pull/102 need to be reverted and show bgp needs to be retained. What you decide about "show ipv6 bgp" is at your discretion. Just be advised that FRR has no directly mapped cli for that.

**Comment by lguohan** [comment]
thanks for your comments. our survey suggests most of our NE prefer show ip/ipv6 bgp commands, so we are going to keep them. If you feel "show bgp" is the way to adopt in the future. Please submit PR to add "show bgp" back.

**Comment by nikos-li** [comment]
@lguohan Please use this PR to do the work and add show bgp back.

**Comment by lguohan** [comment]
it is better for you to add it for your specific need, we do not have much experience on "show bgp"

**Comment by nikos-li** [comment]
@lguohan As reference, this was done as part of https://github.com/Azure/sonic-utilities/issues/102:
- Remove 'bgp' and 'route' commands from under root group (now different commands reside under 'ip' & 'ipv6')
It doesn't require specific knowledge of BGP or experience with it since this is a cli issue. Please kindly assign someone from your team to fix the breakage. Best Regards.

**Comment by rodnymolina** [comment]
I would like to add to Nikos point that for the reasons that he has enumerated above, FRR proceeded to deprecate and eventually eliminate the "show ipv6 bgp" stanza. The result is that FRR today supports a more intuitive and consistent approach: both "show ip bgp ipv4/ipv6" and "show bgp ipv4/ipv6" stanzas are supported.

To address the problem being discuss here, we need to go beyond reverting "show bgp" changes. This is still needed, but it's not enough, coz Quagga and FRR has considerably diverged in this area during the last few months -- Quagga's version used by Sonic only supports "show ip/ipv6 bgp" -- "show bgp ipv4/ipv6" stanza lacks consistency to say the least. Thus, as you can see, we have a problem with all ipv6 commands (and also with some ipv4 ones) as they are not common in Quagga and FRR.

To fully fix this problem we will need to add some code infrastructure to allow our CLI to be aware of the routing-stack being executed, and the corresponding commands being supported by the backends. Either we do it like this (preferable) or we duplicate cli code for as many routing-stacks as Sonic support (ugly).
