### ISSUE TITLE
[unittest] Unable to run unittest locally

### ISSUE THREAD

**Issue by Blueve** [Azure/sonic-utilities#1160]
**Description**

The `README.md` told that we can run unit tests locally by executing `python2 setup.py test`, but it will failed due to some packages are missing.

Is there a guideline to run the tests from scratch? Now, I have to enter `sonic-buildimage` repository and build the python-wheel to get a test result. Since the `sonic-utilties` is an independent repository and it has its own readme document, it is quite confusing me.

**Expected Action For This Issue**

Update `README.md`

**Steps to reproduce the issue**
1. Clone `sonic-buildimage`
1. Enter `src\sonic-utilities`
1. Run `python2 setup.py test`
1. Check the output

**Describe the results you received**
```
jika@jika-vm-01:~/soniccli/consolecli/src/sonic-utilities$ python2 setup.py test
running pytest
Searching for swsssdk>=2.0.1
Reading https://pypi.python.org/simple/swsssdk/
Couldn't find index page for 'swsssdk' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for swsssdk>=2.0.1
error: Could not find suitable distribution for Requirement.parse('swsssdk>=2.0.1')
```

**Describe the results you expected**
Unit test result table and logs.

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```
(paste your output here)
```

**Comment by lguohan** [comment]
@jleveque , can you provide instructions in the README.md for how to run the unit test? It seems i heard multiple people have difficulty to run the sonic utilities unit test.

**Comment by lguohan** [comment]
@Blueve, please try the instructions and let us know if you have any further issue.

**Comment by Blueve** [comment]
Work perfectly! Thanks @jleveque @lguohan ! It's really helpful!
