### ISSUE TITLE
unable to execute unit test for "config interface" commands

### ISSUE THREAD

**Issue by stephenxs** [Azure/sonic-utilities#1301]
**Description**

Unable to execute the unit test for `config interface` sub commands.
For unit testing to work for a command, the fixture `@clicommon.pass_db` is required.
However, the db objects are generated in [interface](https://github.com/Azure/sonic-utilities/blob/master/config/main.py#L2058) subcommand instead of passed by `@clicommon.pass_db`. This is probably because the `namespace` is required in the `config interface` command especially for `MULTI ASIC` feature.

**Steps to reproduce the issue**
1.
2.
3.

**Describe the results you received**

**Describe the results you expected**

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```
(paste your output here)
```

**Comment by anshuv-mfst** [comment]
@stephenxs - could you please recheck; PRs are available.
