### ISSUE TITLE
generate_dump has 'echo' statements that causes collect-techsupport in sonic-mgmt to fail

### ISSUE THREAD

**Issue by sanmalho-git** [Azure/sonic-utilities#1307]
**Description**

In sonic-mgmt pytests, collect-techsupport fixture calls generate_dump and expects only the name of the generated tarfile as output.

```
        res = a_dut.shell("generate_dump -s \"-2 hours\"")
        fname = res['stdout']
        a_dut.fetch(src=fname, dest="logs/{}".format(testname))
```

But commit https://github.com/Azure/sonic-utilities/commit/12e1a0fe713fbeb1ece03523e37f549612b4aa6e#diff-cd1f4d6a5b025b3feb648269fec7b7db4285329bea576baba3734d16b1a1b263 added 'echo' statements to generate_dump.

This causes the code above in sonic-mgmt to break, as we try to fetch the filename with all the echo's, instead of the last line which has the generated tar file from the dump.

**Steps to reproduce the issue**
1. Run sudo generate_dump -s "-1 hours"

**Describe the results you received**
```
admin@sonic:~$ sudo generate_dump -s "-1 hours"
ip link
ip.link
false
ip addr
ip.addr
false
ip rule
ip.rule
false
ip route show table all
ip.route
false
ip neigh
ip.neigh
false
iptables -t nat -nv -L
nat.iptables
false
conntrack -j -L
nat.conntrack
false
conntrack -j -L | wc
nat.conntrackcount
false
conntrack -L
nat.conntrackall
false
conntrack -L | wc
nat.conntrackallcount
false
show nat config
nat.config
false
sonic-db-dump -n 'APPL_DB' -y
APPL_DB.json
false
sonic-db-dump -n 'ASIC_DB' -y
ASIC_DB.json
false
sonic-db-dump -n 'COUNTERS_DB' -y
COUNTERS_DB.json
false
sonic-db-dump -n 'CONFIG_DB' -y
CONFIG_DB.json
false
sonic-db-dump -n 'FLEX_COUNTER_DB' -y
FLEX_COUNTER_DB.json
false
sonic-db-dump -n 'STATE_DB' -y
STATE_DB.json
false
HW Mgmt dump script /usr/bin/hw-management-generate-dump.sh does not exist
/var/dump/sonic_dump_dut1-imm1_20190322_125029.tar.gz
admin@sonic:~$
```

**Describe the results you expected**
```
admin@sonic:~$ sudo generate_dump -s "-1 hours"
/var/dump/sonic_dump_dut1-imm1_20190322_125029.tar.gz
admin@sonic:~$
```

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

Our SONiC codebase is re-based to sonic-buildimage on github upto 12/03/2020

**Comment by anshuv-mfst** [comment]
@lguohan - could you please look into this issue, thanks.

**Comment by lguohan** [comment]
is this related to this pr?

https://github.com/Azure/sonic-utilities/commit/22d79f387728f40e9994d8dcd3397f42dda8a578#diff-cd1f4d6a5b025b3feb648269fec7b7db4285329bea576baba3734d16b1a1b263

**Comment by smaheshm** [comment]
The script has been updated and the issue is not seen any more. 

@sanmalho-git  What test was failing? "show_techsupport" pytest passed with the commit you referenced.

**Comment by sanmalho-git** [comment]
This issue is now fixed.
