### ISSUE TITLE
[sflow] Default sample rate in sflow is not match with CLI spec

### ISSUE THREAD

**Issue by fredyu190011** [Azure/sonic-utilities#1334]
**Description**

When I configure sflow on dut, the default sample rate is not match with CLI spec.

HLD and user guide:

The default sample rate for any interface is (ifSpeed / 1e6) where ifSpeed is in bits/sec. So, the default sample rate based on interface speed is:
1-in-1000 for a 1G link
1-in-10,000 for a 10G link
1-in-40,000 for a 40G link
1-in-50,000 for a 50G link
1-in-100,000 for a 100G link

But, the actual rate per speed is (ifSpeed / 1e7) shown as the following (in sonic-swss/sflowmgr.cpp)
```
#define SFLOW_SAMPLE_RATE_VALUE_400G "40000"
#define SFLOW_SAMPLE_RATE_VALUE_100G "10000"
#define SFLOW_SAMPLE_RATE_VALUE_50G  "5000"
#define SFLOW_SAMPLE_RATE_VALUE_40G  "4000"
#define SFLOW_SAMPLE_RATE_VALUE_25G  "2500"
#define SFLOW_SAMPLE_RATE_VALUE_10G  "1000"
#define SFLOW_SAMPLE_RATE_VALUE_1G   "100"
```

**Comment by maksymbelei95** [comment]
Dear @fredyu190011,

I have checked the issue. As there are no requirements regarding default values of sample rate of sFlow, I think the best way to solve the issue is to change Command Reference according to already defined values in the source code.
I have made PR for the issue, could you review it?

**Comment by fredyu190011** [comment]
Hello @maksymbelei95,

According [SONiC#746](https://github.com/Azure/SONiC/pull/746), they think the default rate should still be "ifSpeed / 1e6".
And I have sent new PR to correct the code in [sonic-swss#1623](https://github.com/Azure/sonic-swss/pull/1623)

**Comment by maksymbelei95** [comment]
@fredyu190011, is there any updates regarding this issue? I see that https://github.com/Azure/sonic-swss/pull/1623 is reviewed, but it still unmerged.

**Comment by maksymbelei95** [comment]
@fredyu190011, as PR https://github.com/Azure/sonic-swss/pull/1623 is currently merged, I think the issue could be closed, isn't it?

**Comment by fredyu190011** [comment]
Hi @maksymbelei95 , I think this issue could be closed.
