### ISSUE TITLE
decode-syseeprom cannot save cache

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-utilities#137]
Although we have the `/var/cache/ssw/decode-syseeprom` folder for saving the eeprom cache, this functionality never works. It seems that there's a bug in the `/usr/bin/decode-syseeprom` script line 115. Need to fix this issue so as to speed up the script read time.

**Comment by jleveque** [comment]
@stcheng: You're correct, the bug is on line 115. `opts.target` does not exist. I looked back through all commits, and it appears that `target` was never a member of `opts`.

Do you know what the cache file name was originally intended to be when this was first designed?

**Comment by stcheng** [comment]
I think we could name it as `syseeprom` or `eeprom`.
