### ISSUE TITLE
[collect-techsupport] 'generate_dump -s <option>' command is broken  

### ISSUE THREAD

**Issue by oxygen980** [Azure/sonic-utilities#1370]
**Description**
generate_dump -s <option>' command is broken,
admin@i:~$ generate_dump -s "-2 hours"
/usr/local/bin/generate_dump: line 879: OPTARG: unbound variable

**Steps to reproduce the issue**
1. Run command 'generate_dump -s "-2 hours"'
2. Shows '/usr/local/bin/generate_dump: line 879: OPTARG: unbound variable'

**Describe the results you received**
admin@i:~$ generate_dump -s "-2 hours"
/usr/local/bin/generate_dump: line 879: OPTARG: unbound variable

**Describe the results you expected**
admin@sonic:~$ sudo generate_dump -s "-1 hours"
/var/dump/sonic_dump_dut1-imm1_20190322_125029.tar.gz

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```

```

**Comment by anshuv-mfst** [comment]
The fix was introduced by Azure/sonic-utilities@bc2d27e , please re-try with this.
