### ISSUE TITLE
Remove references to deprecated platform plugins from utilities_common/util_base.py and PDDF

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-utilities#1459]
#### Description

The old platform plugins are deprecated in favor of the new sonic-platform package. We are in the process of removing references to them moving forward. No new platforms should use the old plugins.

The only remaining references in sonic-utilities are found in `utilities_common/util_base.py` and the PDDF utilities. These shoudl be removed.

**Comment by jleveque** [comment]
@fk410167: Can you please look into this task?

**Comment by fk410167** [comment]
Sure. Please assign this task to me. 
PDDF utilities are using wrappers (so that they are compliant to both 1.0 plugins and 2.0 APIs). Do I have to make it only 2.0 based ?

-Fuzail
