### ISSUE TITLE
variable referenced before assignment in monitor/route_check

### ISSUE THREAD

**Issue by rraghav-cisco** [Azure/sonic-utilities#1550]
We can see this problem by code walk as well. In the file: https://github.com/Azure/sonic-utilities/blob/master/scripts/route_check.py

The variable "adds" should be defined first, before it is used. the other variable "subs" is defined. 

Program 'routeCheck'
  status                       Status failed
  monitoring status            Waiting
  monitoring mode              active
  on reboot                    start
  last exit value              1
  last output                  Traceback (most recent call last):
                                 File "/usr/local/bin/route_check.py", line 463, in <module>
                                   sys.exit(main()[0])
                                 File "/usr/local/bin/route_check.py", line 451, in main
                                   ret, res= check_routes()
                                 File "/usr/local/bin/route_check.py", line 416, in check_routes
                                   print_message(syslog.LOG_ERR, "add: {", json.dumps(adds, indent=4), "}")
                               UnboundLocalError: local variable 'adds' referenced before assignment
                                Failure results: { {
                                   "missed_INTF_TABLE_entries": [
                                       "10.0.0.64/32"
                                   ]
                               } }
                                Failed. Look at reported mismatches above
  data collected               Wed, 07 Apr 2021 15:41:00

**Comment by lguohan** [comment]
@renukamanavalan , can you check?

**Comment by renukamanavalan** [comment]
PR #1551 filed. Thanks for reporting the issue!

**Comment by renukamanavalan** [comment]
Hi Raghav, I am unable to find you in reviewers. Please help review.

**Comment by renukamanavalan** [comment]
PR merged.
