### ISSUE TITLE
Sfputil.py failed to get eeprom data without a cable

### ISSUE THREAD

**Issue by YaoTien** [Azure/sonic-utilities#173]
I got error when I tired to display a port's eeprom which don't plugging any SFP+/QSFP+ cable. 
Is it normally?

admin@sonic:~ $ sudo sfputil show eeprom -p Ethernet0
Traceback (most recent call last):
  File "/usr/bin/sfputil", line 9, in <module>
    load_entry_point('sonic-utilities==1.1', 'console_scripts', 'sfputil')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 430, in eeprom
    output += port_eeprom_data_string_pretty(logical_port_name, dump_dom)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 195, in port_eeprom_data_string_pretty
    result += dict_to_string_pretty(iface_data_dict, 1)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 933: ordinal not in range(128)
admin@sonic:~ $ cat /sys/bus/i2c/devices/11-0050/eeprom | hexdump -C
00000000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
*
00000100
admin@sonic:~$ sudo sfputil version
sfputil version 2.0

**Comment by YaoTien** [comment]
Suggest detect the port is presence or not before read eeprom.

539     def get_eeprom_dict(self, port_num):
540         """Returns dictionary of interface and dom data.
541         format: {<port_num> : {'interface': {'version' : '1.0', 'data' : {...}},
542                                'dom' : {'version' : '1.0', 'data' : {...}}}}
543         """
544
545         if not self.get_presence(port_num):
546             return None
547
548         sfp_data = {}

**Comment by jleveque** [comment]
That is not normal behavior. When trying to display the SFP EEPROM data, there is already a check in place to ensure an EEPROM is present. When trying to reproduce this on a couple different supported platforms with cables disconnected, sfputil does not crash; instead I receive the proper message:

```
admin@sonic:~ $ sudo sfputil show eeprom -p Ethernet0
Ethernet0: SFP EEPROM not detected
```

Which platform are you seeing this on?

**Comment by YaoTien** [comment]
I'm developing on our platform.
I can fix this problem by add a function in own eeprom.py.
Thanks for your help.
