### ISSUE TITLE
Generic Updater fail when apply empty json file

### ISSUE THREAD

**Issue by wen587** [Azure/sonic-utilities#1893]
#### Description
admin@vlab-01:~$ sudo config apply-patch dhcp_empty.json
Patch Applier: Patch application starting.
Patch Applier: Patch: []
Patch Applier: Validating patch is not making changes to tables without YANG models.
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating target config according to YANG models.
Note: Below table(s) have no YANG models:
BGP_PEER_RANGE, BUFFER_PG, BUFFER_POOL, BUFFER_PROFILE, BUFFER_QUEUE, CABLE_LENGTH, CONSOLE_SWITCH, DEVICE_NEIGHBOR_METADATA, DHCP_SERVER, DSCP_TO_TC_MAP, KDUMP, MAP_PFC_PRIORITY_TO_QUEUE, PORT_QOS_MAP, QUEUE, RESTAPI, SCHEDULER, SNMP, SNMP_COMMUNITY, SYSLOG_SERVER, TC_TO_PRIORITY_GROUP_MAP, TC_TO_QUEUE_MAP, TELEMETRY, WRED_PROFILE,
sonic_yang(3):All Keys are not parsed in BGP_NEIGHBOR
dict_keys(['10.0.0.57', '10.0.0.59', '10.0.0.61', '10.0.0.63', 'fc00::72', 'fc00::76', 'fc00::7a', 'fc00::7e'])
sonic_yang(3):exceptionList:["'admin_status'", "'admin_status'", "'admin_status'", "'admin_status'", "'admin_status'", "'admin_status'", "'admin_status'", "'admin_status'", 'Value not found for vrf_name neighbor in 10.0.0.57', 'Value not found for vrf_name neighbor in 10.0.0.59', 'Value not found for vrf_name neighbor in 10.0.0.61', 'Value not found for vrf_name neighbor in 10.0.0.63', 'Value not found for vrf_name neighbor in fc00::72', 'Value not found for vrf_name neighbor in fc00::76', 'Value not found for vrf_name neighbor in fc00::7a', 'Value not found for vrf_name neighbor in fc00::7e']
sonic_yang(3):Data Loading Failed:All Keys are not parsed in BGP_NEIGHBOR
dict_keys(['10.0.0.57', '10.0.0.59', '10.0.0.61', '10.0.0.63', 'fc00::72', 'fc00::76', 'fc00::7a', 'fc00::7e'])
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: Given patch is not valid because it will result in an invalid config

## Steps to reproduce the issue
1. Build up a KVM env
2. Apply empty json file

#### Describe the results you received
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

#### Describe the results you expected
Config replaced successfully.

#### Output of `show version`

```
(paste your output here)
```
admin@vlab-01:~$ show version

SONiC Software Version: SONiC.test.0-dirty-20211014.061123
Distribution: Debian 10.11
Kernel: 4.19.0-12-2-amd64
Build commit: 07c6f26c6
Build date: Thu Oct 14 08:01:03 UTC 2021
Built by: jxie@jingwen-vm-01

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: N/A
Model Number: N/A
Hardware Revision: N/A
Uptime: 02:54:44 up 9 days, 21:33,  1 user,  load average: 0.11, 0.14, 0.16

Docker images:
REPOSITORY                    TAG                            IMAGE ID            SIZE
docker-dhcp-relay             latest                         dcd9aaf8d710        422MB
docker-platform-monitor       latest                         78be754ded11        632MB
docker-platform-monitor       test.0-dirty-20211014.061123   78be754ded11        632MB
docker-snmp                   latest                         fcc7ad433844        457MB
docker-snmp                   test.0-dirty-20211014.061123   fcc7ad433844        457MB
docker-syncd-vs               latest                         acde9aa85dc1        422MB
docker-syncd-vs               test.0-dirty-20211014.061123   acde9aa85dc1        422MB
docker-gbsyncd-vs             latest                         e7972d91338d        422MB
docker-gbsyncd-vs             test.0-dirty-20211014.061123   e7972d91338d        422MB
docker-nat                    latest                         f4e582f89181        429MB
docker-nat                    test.0-dirty-20211014.061123   f4e582f89181        429MB
docker-teamd                  latest                         2027c6cbcf63        427MB
docker-teamd                  test.0-dirty-20211014.061123   2027c6cbcf63        427MB
docker-lldp                   latest                         66c9aa848d9a        455MB
docker-lldp                   test.0-dirty-20211014.061123   66c9aa848d9a        455MB
docker-database               latest                         2a1e78f0a7f4        415MB
docker-database               test.0-dirty-20211014.061123   2a1e78f0a7f4        415MB
docker-router-advertiser      latest                         b54e326161b1        415MB
docker-router-advertiser      test.0-dirty-20211014.061123   b54e326161b1        415MB
docker-macsec                 latest                         6ba82e903391        430MB
docker-macsec                 test.0-dirty-20211014.061123   6ba82e903391        430MB
docker-sonic-mgmt-framework   latest                         c0ebc6980be8        569MB
docker-sonic-mgmt-framework   test.0-dirty-20211014.061123   c0ebc6980be8        569MB
docker-orchagent              latest                         f7c64204021e        445MB
docker-orchagent              test.0-dirty-20211014.061123   f7c64204021e        445MB
docker-sonic-telemetry        latest                         d47bde83d8ad        503MB
docker-sonic-telemetry        test.0-dirty-20211014.061123   d47bde83d8ad        503MB
docker-fpm-frr                latest                         ee70dfcbc57e        445MB
docker-fpm-frr                test.0-dirty-20211014.061123   ee70dfcbc57e        445MB
docker-sflow                  latest                         efecbdb53556        427MB
docker-sflow                  test.0-dirty-20211014.061123   efecbdb53556        427MB

**Comment by ghooo** [comment]
Created issues to fix yang-models:
https://github.com/Azure/sonic-buildimage/issues/9119
https://github.com/Azure/sonic-buildimage/issues/9120
https://github.com/Azure/sonic-buildimage/issues/9121
https://github.com/Azure/sonic-buildimage/issues/9122

**Comment by ghooo** [comment]
all sub-issues have been resolved. closing this issue.
