### ISSUE TITLE
JSON change: remove op for empty table is invalid

### ISSUE THREAD

**Issue by renukamanavalan** [Azure/sonic-utilities#1908]
#### Description

```
Patch Applier: The patch was sorted into 2 changes:
Patch Applier: * [{"op": "remove", "path": "/TACPLUS/global"}]
Patch Applier: * [{"op": "remove", "path": "/TACPLUS"}]
Patch Applier: Applying changes in order.
```

Upon applying first change, the redis removes `"TACPLUS|global"`.
Now no more "TACPLUS"
The second change to remove `"/TACPLUS"` throws in JsonChange.apply, which does "jsonpatch.JsonPatch.apply" as there is no TACPLUS key.

Error message:

Error: can't remove a non-existent object 'TACPLUS
## Steps to reproduce the issue
1. Ensure no TACPLUS key in running config  --(load minigraph can simulate)
2. Apply patch 
`[ { "op": "add", "path": "/TACPLUS", "value": { "global": { "auth_type": "login" } } } ]`
3. Apply patch
`[ { "op": "remove", "path": "/TACPLUS" } ]`

This should fail as below.
```
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: can't remove a non-existent object 'TACPLUS'

```
#### Output of `show version`

```
(paste your output here)
```

**Comment by ghooo** [comment]
addressed in #1923
