### ISSUE TITLE
GenericUpdater: Support non-strict mode

### ISSUE THREAD

**Issue by renukamanavalan** [Azure/sonic-utilities#1914]
#### Description
As YANG models are evolving at this phase, so as not to block our progress, can we go for an option in command line, that can be used to select “non-strict-mode” or not. Note: Default is strict.
 
Patch_applier -n/--non-strict …
 
**In strict mode**
1.	For tables with YANG defined, the running config MUST match
2.	Patch can be applied only for tables with YANG model
3.	Use strict mode to find & file issues for incorrect/missing YANG
 
**In non-strict mode:**
1.	For tables with YANG, we only validate fields that are defined in YANG. For fields in running config but not in YANG, we skip validation.  -- @Mohamed Ghoneim, has a way of accomplishing
2.	For tables w/o YANG
a.	We skip complete validation
b.	We allow patch application
 
**Testers:**
1.	Use strict/default mode to find & file issue
2.	Use non-strict mode to progress with test cases
3.	Mark test cases that fail strict mode and *track* them in a separate tracking page and tag them with corresponding issue
 
**YANG developers:**
For each issue:
1.	Update YANG
2.	Ensure the test cases tagged with this issue pass
a.	Update test case, if needed
3.	Raise PR & upon commit, update the tracking page
 
At a point in future, we can de-activate this option and make strict-mode as the only possibility.

## Steps to reproduce the issue
1.
2.
3.

#### Output of `show version`

```
(paste your output here)
```

**Comment by ghooo** [comment]
non-strict mode added
