### ISSUE TITLE
[sonic_installer] should not return fail (rc=1) if new image is the same as what has been installed

### ISSUE THREAD

**Issue by maggiemsft** [Azure/sonic-utilities#200]
sonic_installer return 1 if the upgrade new image is the same as what has been installed

**Steps to reproduce the issue**
1. use sonic_installer to upgrade SONiC to same image version
2.
3.

**Describe the results you received**
shell returns 1 which indicate fail

**Describe the results you expected**
could it exit with success while do not do "reinstall"?

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```
(paste your output here)
```

**Comment by jleveque** [comment]
Root cause of nonzero exit code is in sonic-buildimage/installer/x86_64/install.sh.

PR to fix this is at: https://github.com/Azure/sonic-buildimage/pull/1389
