### ISSUE TITLE
generic_config_updater: Add Rack: Issues

### ISSUE THREAD

**Issue by renukamanavalan** [Azure/sonic-utilities#2007]
#### Description

Applying a generic patch for addRack fails for 2 reasons
1) The new interfaces should be ordered to be added at the start before addition of any other object.
    Vice versa, for remove rack, the interface objects removal should be ordered to go as last.
2) Do NOT split update/add of a single object into many as shown below.
    This blocks BGP coming up for this new IP.
   Sample:
   i/p:
```
    {
        "op": "add",
        "path": "/BGP_NEIGHBOR/10.0.0.33",
        "value": {
            "admin_status": "up",
            "asn": "64001",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "10.0.0.32",
            "name": "ARISTA01T0",
            "nhopself": "0",
            "rrclient": "0"
        },
    {
        "op": "add",
        "path": "/BGP_NEIGHBOR/fc00::42",
        "value": {
            "admin_status": "up",
            "asn": "64001",
            "holdtime": "10",
            "keepalive": "3",
            "local_addr": "fc00::41",
            "name": "ARISTA01T0",
            "nhopself": "0",
            "rrclient": "0"
        }
    },

```
Patch Applier: Applying 16 changes in order:
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33", "value": {"admin_status": "up"}}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/asn", "value": "64001"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/holdtime", "value": "10"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/keepalive", "value": "3"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/local_addr", "value": "10.0.0.32"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/name", "value": "ARISTA01T0"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/nhopself", "value": "0"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/rrclient", "value": "0"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42", "value": {"admin_status": "up"}}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/asn", "value": "64001"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/holdtime", "value": "10"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/keepalive", "value": "3"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/local_addr", "value": "fc00::41"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/name", "value": "ARISTA01T0"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/nhopself", "value": "0"}]
Patch Applier:   * [{"op": "add", "path": "/BGP_NEIGHBOR/fc00::42/rrclient", "value": "0"}]
    },

## Steps to reproduce the issue
1. Create two config_db.json one with & one w/o a T0
2. Load the config w/o T0; Ensure BGP is started for all (config bgp startup all)
3. Use jsonpatch.JsonPatch.from_diff to create a patch (w/o to with) for addRack
4. Use "config apply-patch " to apply the created patch
5. Note: BGP session for the added port don't come up and never.

#### Output of `show version`

```
(paste your output here)
```

**Comment by ghooo** [comment]
The problem is in splitting adding the neighbor in multiple steps:
```
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33", "value": {"admin_status": "up"}}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/asn", "value": "64001"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/holdtime", "value": "10"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/keepalive", "value": "3"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/local_addr", "value": "10.0.0.32"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/name", "value": "ARISTA01T0"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/nhopself", "value": "0"}]
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/rrclient", "value": "0"}]
```

The reason is all fields in a neighbor are create-only field, i.e. they can only be created when the parent is created but they cannot be updated.

So if we start with 
```
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33", "value": {"admin_status": "up"}}]
```
Then directly add the other fields e.g.:
```
Patch Applier: * [{"op": "add", "path": "/BGP_NEIGHBOR/10.0.0.33/asn", "value": "64001"}]
```

This change does not take effect. Hence marking the fields with `create-only` solves the problem.
