### ISSUE TITLE
[GCU] Check if BGP_INTERNAL_NEIGHBOR, BGP_MONITORS, BGP_PEER_RANGE, BGP_VOQ_CHASSIS_NEIGHBOR fields are create-only

### ISSUE THREAD

**Issue by ghooo** [Azure/sonic-utilities#2029]
#### Description
Create-Only fields are only created with their parent, but cannot be modified later.

## Steps to reproduce the issue
1.
2.
3.

#### Output of `show version`

```
(paste your output here)
```

**Comment by ghooo** [comment]
@qiluo-msft I didn't find a YANG table for BGP_INTERNAL_NEIGHBOR nor BGP_VOQ_CHASSIS_NEIGHBOR. I need to know the fields under these tables so I can double check if they are create-only or not.

**Comment by qiluo-msft** [comment]
@ganglyu These tables are missing yang models and also minigraph parsing/validation unit test.

**Comment by ganglyu** [comment]
https://github.com/Azure/sonic-buildimage/issues/10157
https://github.com/Azure/sonic-buildimage/issues/10158
I have created above issues to trace this requirement, and I will discuss with BGP owner and Multi-asic team to add these Yang models.

**Comment by ganglyu** [comment]
> @qiluo-msft I didn't find a YANG table for BGP_INTERNAL_NEIGHBOR nor BGP_VOQ_CHASSIS_NEIGHBOR. I need to know the fields under these tables so I can double check if they are create-only or not.

https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-config-engine/minigraph.py#L727
Please refer to above link, it seems that BGP_INTERNAL_NEIGHBOR and BGP_VOQ_CHASSIS_NEIGHBOR are similar, and the fields under these tables are: name, local_addr, rrclient, holdtime, keepalive, nhopself, admin_status and asn.
