### ISSUE TITLE
Does sfputil/main.py get platform success in current version??

### ISSUE THREAD

**Issue by philipwangCP** [Azure/sonic-utilities#215]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
sfputil/main.py platform_key define maybe not revise for new design.

**Description**
In sfputil/main.py HWSKU_KEY and PLATFORM_KEY define:
HWSKU_KEY = "DEVICE_METADATA['localhost']['hwsku']"
PLATFORM_KEY = 'platform'

**Steps to reproduce the issue**
1.  sudo sfputil version 

**Describe the results you received**
Failed to load platform module 'sfputil': [Errno 2] No such file or directory

**Describe the results you expected**
sfputil version 2.0

**Additional information you deem important (e.g. issue happens only occasionally)**
this issue is get platform string fail cause sfputil not find.

**Comment by jleveque** [comment]
@taoyl-ms: It appears you missed sfputil/main.py in PR https://github.com/Azure/sonic-utilities/pull/205. Can you please take care of this?

**Comment by philipwangCP** [comment]
sfputil/main.py maybe not revise as psuutil/main.py. And psuutil/main.py has updated few days ago.

**psuutil/main.py**
31: HWSKU_KEY = **'DEVICE_METADATA.localhost.hwsku'**
32: PLATFORM_KEY = **'DEVICE_METADATA.localhost.platform'**
...
71: def get_platform_and_hwsku():
72:     try:
73:         proc = subprocess.Popen(**[SONIC_CFGGEN_PATH, '-H', '-v', PLATFORM_KEY]**,

**sfputil/main.py**
31: HWSKU_KEY = **"DEVICE_METADATA['localhost']['hwsku']"**
32: PLATFORM_KEY = **'platform'**
...
289: def get_platform_and_hwsku():
290:     try:
291:         proc = subprocess.Popen(**[SONIC_CFGGEN_PATH, '-v', PLATFORM_KEY]**,

**Comment by philipwangCP** [comment]
sfputil/main.py miss revise.

**Comment by jleveque** [comment]
Fixed in https://github.com/Azure/sonic-utilities/pull/216
