### ISSUE TITLE
Add port channel status to teamshow?

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-utilities#23]
```
Flags: A - active, I - inactive, N/A - Not Available, S - selected, D - deselected
  No.  Team Dev       Protocol    Ports
-----  -------------  ----------  ---------------------------
   24  PortChannel24  LACP(A)     Ethernet28(S) Ethernet24(S)
   48  PortChannel48  LACP(A)     Ethernet52(S) Ethernet48(S)
   16  PortChannel16  LACP(A)     Ethernet20(S) Ethernet16(S)
   32  PortChannel32  LACP(A)     Ethernet32(S) Ethernet36(S)
   56  PortChannel56  LACP(A)     Ethernet60(S) Ethernet56(S)
   40  PortChannel40  LACP(A)     Ethernet44(S) Ethernet40(S)
    0  PortChannel0   LACP(A)     Ethernet0(D) Ethernet4(S)
    8  PortChannel8   LACP(A)     Ethernet8(S) Ethernet12(S)
```

It appears that `PortChannel0` is **DOWN** due to the min-links setting. I doubt if we need to display the UP/DOWN status of the port channel in this `teamshow` utility.

**Comment by stcheng** [comment]
It makes sense that the Protocol is **A(Active)** because the LACP protocol is still running.

**Comment by lguohan** [comment]
we still need a flag to indicate whether the lag port is up or down.

**Comment by stcheng** [comment]
@sihuihan88

**Comment by sihuihan88** [comment]
Does it mean that we add another column called "Status" which will have value Up or Down to indicate the portchannel status as following as an example?

 No.  Team Dev       Protocol    Ports                                  Status
-----  -------------  ----------  ---------------------------   ------------------------------
 24  PortChannel24  LACP(A)     Ethernet28(S) Ethernet24(S)    Up 
  0  PortChannel0   LACP(A)     Ethernet0(D) Ethernet4(S)         Down

**Comment by stcheng** [comment]
```
Flags: A - active, I - inactive, N/A - Not Available, S - selected, D - deselected, U - up, D - down
  No.  Team Dev       Protocol    Ports
-----  -------------  ----------  ---------------------------
   24  PortChannel24  LACP(AU)     Ethernet28(S) Ethernet24(S)
   48  PortChannel48  LACP(AU)     Ethernet52(S) Ethernet48(S)
   16  PortChannel16  LACP(AU)     Ethernet20(S) Ethernet16(S)
   32  PortChannel32  LACP(AU)     Ethernet32(S) Ethernet36(S)
   56  PortChannel56  LACP(AD)     Ethernet60(S) Ethernet56(S)
   40  PortChannel40  LACP(AD)     Ethernet44(S) Ethernet40(S)
    0  PortChannel0   LACP(AD)     Ethernet0(D) Ethernet4(S)
    8  PortChannel8   LACP(AD)     Ethernet8(S) Ethernet12(S)
```

it could be something like this.

the status could be get from the database.

**Comment by sihuihan88** [comment]
https://github.com/Azure/sonic-utilities/pull/31 resolves this.
