### ISSUE TITLE
mlnx-msn2100: show platform syseeprom outputs control characters

### ISSUE THREAD

**Issue by nikos-github** [Azure/sonic-utilities#371]
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 527
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  64 MSN2100^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@\
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
Part Number          0x22  20 MSN2100-CB2FO^@^@^@^@^@^@^@
Serial Number        0x23  24 MT1734X00415^@^@^@^@^@^@^@^@^@^@^@^@
Base MAC Address     0x24   6 EC:0D:9A:4E:5A:00
Manufacture Date     0x25  19 08/21/2017 14:32:04
Device Version       0x26   1 0
MAC Addresses        0x2A   2 128
Manufacturer         0x2B   8 Mellanox
Vendor Extension     0xFD  36
Vendor Extension     0xFD 164
Vendor Extension     0xFD  36
Vendor Extension     0xFD  36
Vendor Extension     0xFD  36
Platform Name        0x28  18 x86_64-mlnx_x86-r0
ONIE Version         0x29  21 2016.11-5.1.0012-9600
CRC-32               0xFE   4 0x03683E96
(checksum valid)

**Comment by andriymoroz-mlnx** [comment]
could you please test on version from October, 24 or newer? There were some fixes for eeprom plugin
if didn't help please provide output of
```
cat /sys/devices/platform/i2c_mlxcpld.1/i2c-1/i2c-8/8-0051/eeprom | hexdump
```

and 
```
cat /sys/devices/platform/i2c_mlxcpld.1/i2c-1/i2c-16/16-0051/eeprom | hexdump
```

**Comment by nikos-github** [comment]
@andriymoroz-mlnx Sure. We also have a build from Nov 5th which I will load up in our lab as soon as some other tests finish and will let you know.

**Comment by nikos-github** [comment]
@andriymoroz-mlnx Same issue with a build from Nov 5th. Including the requested output and sh ver at end.

root@sonic:/home/admin# cat /sys/devices/platform/i2c_mlxcpld.1/i2c-1/i2c-8/8-0051/eeprom | hexdump
0000000 6c54 4976 666e 006f 0201 210f 4d40 4e53
0000010 3132 3030 0000 0000 0000 0000 0000 0000
0000020 0000 0000 0000 0000 0000 0000 0000 0000
*
0000040 0000 0000 0000 0000 0000 0000 2200 4d14
0000050 4e53 3132 3030 432d 3242 4f46 0000 0000
0000060 0000 2300 4d18 3154 3337 5834 3030 3134
0000070 0035 0000 0000 0000 0000 0000 2400 ec06
0000080 9a0d 5a4e 2500 3013 2f38 3132 322f 3130
0000090 2037 3431 333a 3a32 3430 0126 2a00 0002
00000a0 2b80 4d08 6c65 616c 6f6e fd78 0024 8100
00000b0 0019 0116 0301 006c 4d00 4e4c 0258 0c01
00000c0 0e05 1002 0006 0000 0000 0000 0000 0000
00000d0 fd00 00a4 8100 0019 0092 0103 0021 4d00
00000e0 3154 3337 5834 3030 3134 0035 0000 0000
00000f0 0000 0000 0000 4d00 4e53 3132 3030 432d
0000100 3242 4f46 0000 0000 0000 4100 0038 0000
0000110 a98c 42ad 6c75 646c 676f 4520 6874 3120
0000120 3030 0000 0000 0000 0000 0000 0000 0000
0000130 0000 0000 0000 0000 0000 0000 0000 0000
*
0000150 0000 0000 5a00 0000 0800 4d34 4e53 3132
0000160 3030 0000 0000 0000 0000 0000 0000 0000
0000170 0000 0000 0000 fd00 0024 8100 0019 0010
0000180 0503 00e8 0000 0000 0000 0000 0000 0000
0000190 0000 0000 0000 0000 0000 0000 fd00 0024
00001a0 8100 0019 001e 0211 00c9 0d00 0000 0000
00001b0 0000 ec00 9a0d 5a4e 0000 ec80 9a0d 0003
00001c0 5a4e fd00 0024 8100 0019 0012 0601 0085
00001d0 0000 0046 0800 0500 0505 0005 0000 0000
00001e0 0000 0000 0000 0000 2800 7812 3638 365f
00001f0 2d34 6c6d 786e 785f 3638 722d 2930 3215
0000200 3130 2e36 3131 352d 312e 302e 3130 2d32
0000210 3639 3030 04fe 6803 963e 0000 0000 0000
0000220 0000 0000 0000 0000 0000 2900 3520 302e
0000230 312e 3034 0034 0000 0000 0000 0000 0000
0000240 0000 0000 0000 0000 0000 0000 fe00 e604
0000250 d7ad 00fb 0000 0000 0000 0000 0000 0000
0000260 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000
root@sonic:/home/admin# cat /sys/devices/platform/i2c_mlxcpld.1/i2c-1/i2c-16/16-0051/eeprom | hexdump
0000000 1600 0101 8203 0000 4c4d 584e 0102 050c
0000010 020e 0000 0000 0000 0000 0000 0000 0000
0000020 9200 0300 e901 0000 544d 3731 3932 3058
0000030 3938 3534 0000 0000 0000 0000 0000 0000
0000040 4153 3030 3432 3633 0000 0000 0000 0000
0000050 0000 0000 3141 0000 c000 ad11 5043 2055
0000060 3858 2036 4653 0046 0000 0000 0000 0000
0000070 0000 0000 0000 0000 0000 0000 0000 0000
*
0000090 0000 0000 0000 0000 0000 0000 0000 005e
00000a0 0000 0000 5043 2055 3858 2036 4653 0046
00000b0 0000 0000 0000 0000 0000 0000 0000 0000
00000c0 1000 0300 e805 0000 0000 0000 0000 0000
00000d0 0000 0000 0000 0000 0000 0000 0000 0000
00000e0 1e00 1100 1f02 0000 000d 0000 0000 0000
00000f0 0dec 659a 04d0 0800 0dec 039a 6500 04d0
0000100 1200 0100 d406 0000 0100 0000 0008 0505
0000110 0000 0000 0000 0000 0000 0000 0000 0000
0000120 0a00 0100 c807 0000 0200 0024 0000 0000
0000130 0000 0000 0000 0000 0000 0000 0000 0000
*
0001000
root@sonic:/home/admin# show ver
SONiC Software Version: SONiC.master.0-dirty-20181106.071407
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 4157f1d
Build date: Tue Nov  6 17:03:06 UTC 2018
Built by: nikos@bs101-01r

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-orchagent-mlnx      latest                           2ffc8da2a392        260.1 MB
docker-orchagent-mlnx      master.0-dirty-20181106.071407   2ffc8da2a392        260.1 MB
docker-syncd-mlnx          latest                           92a8f9070cb5        361.3 MB
docker-syncd-mlnx          master.0-dirty-20181106.071407   92a8f9070cb5        361.3 MB
docker-dhcp-relay          latest                           4928d121937b        253.8 MB
docker-dhcp-relay          master.0-dirty-20181106.071407   4928d121937b        253.8 MB
docker-database            latest                           ea75caee0ad5        252.5 MB
docker-database            master.0-dirty-20181106.071407   ea75caee0ad5        252.5 MB
docker-snmp-sv2            latest                           c64b943a842d        291.3 MB
docker-snmp-sv2            master.0-dirty-20181106.071407   c64b943a842d        291.3 MB
docker-teamd               latest                           6d6dcb2c9cb6        258.1 MB
docker-teamd               master.0-dirty-20181106.071407   6d6dcb2c9cb6        258.1 MB
docker-router-advertiser   latest                           291eac912750        250.2 MB
docker-router-advertiser   master.0-dirty-20181106.071407   291eac912750        250.2 MB
docker-platform-monitor    latest                           44a87c3ab285        283.6 MB
docker-platform-monitor    master.0-dirty-20181106.071407   44a87c3ab285        283.6 MB
docker-lldp-sv2            latest                           26780c50cedf        271.2 MB
docker-lldp-sv2            master.0-dirty-20181106.071407   26780c50cedf        271.2 MB
docker-fpm-frr             latest                           cf556d98266a        264.9 MB
docker-fpm-frr             master.0-dirty-20181106.071407   cf556d98266a        264.9 MB

**Comment by andriymoroz-mlnx** [comment]
@nikos-github, could you please confirm the issue is fixed?

**Comment by nikos-github** [comment]
Confirmed.
