### ISSUE TITLE
show interface status, show platform summary and other cmds are broken

### ISSUE THREAD

**Issue by nikos-github** [Azure/sonic-utilities#403]
The https://github.com/Azure/sonic-utilities/pull/298 commit is breaking show commands for any port_config.ini that doesn't have an alias in it.

Alias is optional in sonic.

This is a blocker since platform/OS stability is compromised and identification as well as status for deployment is not possible.

show interface status error:

root@sonic:/# show interface status
Traceback (most recent call last):
File "/usr/bin/show", line 9, in <module>
  load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
  return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
  return ep.load()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
  return self.resolve()
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
  module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/lib/python2.7/dist-packages/show/main.py", line 199, in <module>
  iface_alias_converter = InterfaceAliasConverter()
File "/usr/lib/python2.7/dist-packages/show/main.py", line 64, in __init__
  self.port_dict[port_name]['alias']):
KeyError: 'alias'

show platform summary syslog error:
Dec 05 05:08:31 spine-1 aos[5216]:     iface_alias_converter = InterfaceAliasConverter()
Dec 05 05:08:31 spine-1 aos[5216]:   File "/usr/lib/python2.7/dist-packages/show/main.py", line 64, in __init__
Dec 05 05:08:31 spine-1 aos[5216]:     self.port_dict[port_name]['alias']):
Dec 05 05:08:31 spine-1 aos[5216]: KeyError: 'alias'

**Comment by jleveque** [comment]
@paavaanan, @padmanarayana: Please add logic to check for the existence of the "alias" field before all attempts to access it in order to prevent this crash.

Per our spec, https://github.com/Azure/SONiC/wiki/Configuration, the 'alias' field is optional in ConfigDB. Therefore, we must gracefully handle the case where it doesn't exist.

**Comment by nikos-github** [comment]
Fixed by https://github.com/Azure/sonic-utilities/pull/405. Fix to verified once we have our new internal image.

**Comment by jleveque** [comment]
@nikos-github: FYI, sonic-buildimage submodule update containing https://github.com/Azure/sonic-utilities/pull/405 in PR here: https://github.com/Azure/sonic-buildimage/pull/2376
