### ISSUE TITLE
Portstat : TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by maq123** [Azure/sonic-utilities#41]
HW : 
```
    "aboot_platform": "x86_64-arista_7050_qx32s", 
    "aboot_version": "4.0.4-2086886", 
    "aboot_machine": "arista_7050_qx32s", 
    "aboot_build_date": "2014-09-25T06:28:52.000000000", 
    "minigraph_hwsku": "Arista-7050-QX32S"
```

Error 

```
root@sonic:/usr/share/sonic/device/x86_64-arista_7050_qx32s# portstat 
Traceback (most recent call last):
  File "/usr/bin/portstat", line 333, in <module>
    main()
  File "/usr/bin/portstat", line 286, in main
    cnstat_dict = portstat.get_cnstat()
  File "/usr/bin/portstat", line 80, in get_cnstat
    for port in natsorted(counter_port_name_map):
  File "/usr/lib/python2.7/dist-packages/natsort/natsort.py", line 328, in natsorted
    key=natsort_keygen(key, alg=alg))
TypeError: 'NoneType' object is not iterable
```

**Comment by sihuihan88** [comment]
Can you use sudo generate_dump and upload the file under /var/dump to provide more information?

**Comment by maq123** [comment]
Here it is 
https://drive.google.com/open?id=0B4oX9-NaEpHkZTdCSkk5VkJySnM

**Comment by sihuihan88** [comment]
Thanks for providing the information. We find that there are some platform related files missing for arista_7050_qx32s and we are working with Arista to get the needed information as soon as possible. We will keep you posted. BTW, arista_7050_qx32 devices work well. That is also an option to use at the same time.

**Comment by maq123** [comment]
ok, thanks for info. Well, I only have 32S in my lab :)

**Comment by maq123** [comment]
any chance to tell when this has a chance to be resolved? Would be nice to know if it could be 1-2 weeks or maybe more than a month.

**Comment by stcheng** [comment]
@maq123 Hi, @sihuihan88 is on vacation right now. I will follow up with this. According to my understanding, this issue won't last more than two weeks.

**Comment by maq123** [comment]
@stcheng Thx for an update :)

**Comment by stcheng** [comment]
@maq123 https://github.com/Azure/sonic-buildimage/pull/597 This pull request is to address the support for the platform `x86_64-arista_7050_qx32s`. We need to evaluate both this pull request and the Broadcom SAI packages which we will update later.

**Comment by maq123** [comment]
hi @stcheng , thanks for info. looking forward for the build then:)

**Comment by stcheng** [comment]
@maq123 Hello, after working with Arista to finish all the platform supporting files, we have make it successful for SONiC to running on Arista-7050-QX32S platform. Once the two pull requests get merged, https://github.com/Azure/sonic-buildimage/pull/671 and https://github.com/Azure/sonic-buildimage/pull/674.

**Comment by maq123** [comment]
@stcheng good! thx for info  :)

**Comment by jleveque** [comment]
@maq123: I believe this issue can safely be closed, but I wanted your input. Could you please confirm that this issue is resolved for you? Thanks.

**Comment by maq123** [comment]
@jleveque sorry, I managed to get another piece of hardware (s6000) to play with SONiC and getting it running on Arista went bit down in my work queue list ;)
If you are interested in my feedback I can verify it on my HW but this might take some time.

**Comment by jleveque** [comment]
@maq123: Thanks for the quick reply. Portstat appears to work fine on the Arista-7050-QX32S running the July 25 build of SONiC in our lab, so I am going to close this.
