### ISSUE TITLE
SONiC AS5712 : "show interface status <INTERFACENAME>" is throwing error. 

### ISSUE THREAD

**Issue by Priya-NS** [Azure/sonic-utilities#427]
SYMPTOM 
======= 
SONiC AS5712 : "show interface status <INTERFACENAME>" is throwing error. 

TOPOLOGY 
========== 
AS5712 DUT 

STEPS TO REPRODUCE 
================== 
1. Bring Up the DUT with default configuration and with the latest build SONiC.201811.0-38d0051 
2. Execute the command "show interface status <INTERFACENAME>" in AS5712. Observe that it is throwing error. 

root@SONIC:~# show interfaces status Ethernet39 
Traceback (most recent call last): 
  File "/usr/bin/intfutil", line 204, in <module> 
    main(sys.argv[1:]) 
  File "/usr/bin/intfutil", line 197, in main 
    interface_stat = IntfStatus(intf_name) 
  File "/usr/bin/intfutil", line 129, in __init__ 
    appl_db_keys = appl_db_keys_get(self.appl_db, intf_name) 
  File "/usr/bin/intfutil", line 41, in appl_db_keys_get 
    appl_db_keys = db.keys(appl_db.APPL_DB, "PORT_TABLE:%s" % intf_name) 
NameError: global name 'db' is not defined 

EXPECTED BEHAVIOR: 
================== 
1. As per the Help text, the command should work. 
root@SONIC:~# show interfaces status flejwlfj kjflew 
Usage: show interfaces status [OPTIONS] [INTERFACENAME] 

Error: Got unexpected extra argument (kjflew) 
2. The same command is working in other SONiC DUT of AG9032v1. 
root@sonic:~# show platform summary 
Platform: x86_64-delta_ag9032v1-r0 
HwSKU: Delta-ag9032v1 
ASIC: broadcom 
root@sonic:~# show interfaces status Ethernet4 
  Interface Lanes Speed MTU Alias Oper Admin 
----------- ----------- ------- ----- -------------- ------ ------- 
  Ethernet4 45,46,47,48 N/A 9100 hundredGigE1/2 down up 

REPRODUCIBILITY 
=============== 
3 out of 3 

BUILD SIGNATURE 
=============== 

root@SONIC:/home/admin# show version 
SONiC Software Version: SONiC.201811.0-38d0051 
Distribution: Debian 9.6 
Kernel: 4.9.0-8-amd64 
Build commit: 38d0051 
Build date: Tue Jan 1 07:09:13 UTC 2019 
Built by: vmuser@server1

**Comment by kirankella** [comment]
It needs a bug fix in intfutil script in the function app_db_keys_get() function when getting the keys for a specific interface.
I am submitting Pull Request for this shortly.

**Comment by kirankella** [comment]
Changes to fix this issue are made as part of https://github.com/Azure/sonic-utilities/pull/424
