### ISSUE TITLE
portstat shows result in wrong format before calling portstat -c the first time

### ISSUE THREAD

**Issue by taoyl-ms** [Azure/sonic-utilities#44]
Here is a portstat result before portstat -c:
![sudo](https://cloud.githubusercontent.com/assets/22916085/25636219/9fc68990-2f35-11e7-8c60-071309021b0a.png)

Here is the correct format after calling portstat -c:
![su](https://cloud.githubusercontent.com/assets/22916085/25636284/c7d7b18e-2f35-11e7-90d0-882f071dc712.png)

We can see in the first result column indices are two column shifted.

**Comment by sihuihan88** [comment]
https://github.com/Azure/sonic-utilities/pull/50 resolves this.
