### ISSUE TITLE
add option to print out presence of transceiver in sfputil

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-utilities#70]

**Comment by stcheng** [comment]
it's better to replace the current `show interface summary` command to display a table of sufficient information including all the related information. e.g. admin/oper status, speed, MTU, SFP status, lane mapping, etc.

**Comment by lguohan** [comment]
what is lane mapping? 

show interface summary is targeted to the NE, lane mapping is usually not their focus.

**Comment by stcheng** [comment]
agree. lane mapping is not necessary.
