### ISSUE TITLE
Show interface information in "show bgp summary" command

### ISSUE THREAD

**Issue by daall** [Azure/sonic-utilities#710]
**Description**

It would be helpful if `show bgp sum` also showed some description of the neighbor as well as the IP address in the output. This is useful in scenarios where you want to shutdown a bgp session between the current device and a specific neighbor but you don't know the IP of that neighbor off the top of your head.

**Describe the results you received**
```
admin@str-s6000-on-5:~$ show bgp sum

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 12657
RIB entries 12807, using 2001 KiB of memory
Peers 4, using 83 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
10.0.0.57       4      64600   30558   30563        0    0    0 22:47:39         6400
10.0.0.59       4      64600   30557   30563        0    0    0 22:47:39         6400
10.0.0.61       4      64600   30559   30560        0    0    0 22:47:39         6400
10.0.0.63       4      64600   30556   30561        0    0    0 22:47:39         6400

Total number of neighbors 4
```

**Describe the results you expected**
```
admin@str-s6000-on-5:~$ show bgp sum

IPv4 Unicast Summary:
BGP router identifier 10.1.0.32, local AS number 65100 vrf-id 0
BGP table version 12657
RIB entries 12807, using 2001 KiB of memory
Peers 4, using 83 KiB of memory
Peer groups 2, using 128 bytes of memory

Neighbor   Neighbor IP        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
SOMET101   10.0.0.57          4      64600   30558   30563        0    0    0 22:47:39         6400
SOMET102   10.0.0.59          4      64600   30557   30563        0    0    0 22:47:39         6400
SOMET103   10.0.0.61          4      64600   30559   30560        0    0    0 22:47:39         6400
SOMET104   10.0.0.63          4      64600   30556   30561        0    0    0 22:47:39         6400

Total number of neighbors 4
```

**Additional information you deem important (e.g. issue happens only occasionally)**
This information is currently available via `show ip int`/`show ipv6 int` but it would be more convenient if this information was displayed in the `show bgp sum` command.

**Comment by lguohan** [comment]
where do we get the neighbor information then? do we have those in the bgp configuration?

**Comment by prsunny** [comment]
There was a recent enhancement to give this details as part of 'show in status'. I think, it would do the required as we don't want to overload 'show ip bgp summ' output

**Comment by daall** [comment]
@prsunny Do you know what PR that is in?

@lguohan The show script already has a `get_bgp_peer()` method so that information is already accessible. I think the tricky part is that the command is using FRR's `show ip bgp sum` command, so we don't have that level of control over the output. To implement this as part of our `show bgp summary` command we'd have to post-process the FRR output to include an extra column with the neighbor information, which would be a complicated change.

I think if the enhancement that Prince is referencing makes that info easily accessible then it's probably best to use that and keep `show bgp summary` simple. If someone feels strongly about including the neighbor name along with the IP in `show bgp summary` they can give it a try with the above method.

**Comment by prsunny** [comment]
https://github.com/Azure/sonic-utilities/pull/597

**Comment by daall** [comment]
Let's go ahead and use that then! Closed.
