### ISSUE TITLE
show ipv6 bgp sum

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-utilities#75]

**Comment by pavel-shirshov** [comment]
What is wrong with the current one?

vtysh -c 'sh ipv6 bgp summ'
BGP router identifier 10.1.0.32, local AS number 65100
RIB entries 1, using 112 bytes of memory
Peers 64, using 291 KiB of memory

Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
fc00::2         4 65200       0       0        0    0    0 never    Active     
fc00::6         4 65200       0       0        0    0    0 never    Active     
fc00::a         4 65200       0       0        0    0    0 never    Active

**Comment by jleveque** [comment]
Nothing. It just needs to be wrapped in our 'show' command. That's the purpose of this issue.

**Comment by lguohan** [comment]
correct, sorry for the brevity

**Comment by nikos-li** [comment]
This issue should not be resolved. Sonic should not provide a "show ipv6 bgp ...".

**Comment by jleveque** [comment]
@nikos-li: I disagree. I believe this issue *should* be closed as it is no longer relevant because it has been resolved in the codebase. You have opened issue https://github.com/Azure/sonic-utilities/issues/108 which will be the forum for discussing further modifications to this feature.

**Comment by jleveque** [comment]
Resolved in https://github.com/Azure/sonic-utilities/pull/102
