### ISSUE TITLE
[watermark] show queue watermark multicast OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-utilities#987]
**Description**
Receiving OverflowError: cannot convert float infinity to integer when:

**Steps to reproduce the issue**

**1. Run iface_mode test case:**
`ansible-playbook test_sonic.yml -i /sonic-mgmt/ansible/lab  -e testbed_name= -e testcase_name=iface_mode -e testbed_file=/sonic-mgmt/ansible/testbed.csv -e ptf_host=ptf_vms1`

**2. Execute command through SONiC CLI:**
` show queue watermark multicast`

**Describe the results you received**
Error appears: 
```
Traceback (most recent call last):
  File "/usr/bin/watermarkstat", line 281, in <module>
    main()
  File "/usr/bin/watermarkstat", line 276, in main
    watermarkstat.print_all_stat(table_prefix, args.type)
  File "/usr/bin/watermarkstat", line 226, in print_all_stat
    self.build_header(type)
  File "/usr/bin/watermarkstat", line 191, in build_header
    self.min_idx = int(min_idx)
OverflowError: cannot convert float infinity to integer
```

**Describe the results you expected**
Test iface_mode passed 

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**
SONiC Software Version: SONiC.HEAD.714-dirty-20200712.182711
Distribution: Debian 10.4
Kernel: 4.19.0-9-2-amd64
Build commit: 8ea03eed
```
(paste your output here)
```

**Comment by bratashX** [comment]
Fix: https://github.com/Azure/sonic-utilities/pull/1147

**Comment by SavchukRomanLv** [comment]
Fixed
